### ISSUE TITLE
ImpoerError

### ISSUE THREAD

**Issue by Liseria** [qcwthu/Continual_Fewshot_Relation_Learning#4]
I follow the steps but when bash runall.sh it tells me cannot import name logging from transformers.utils.

**Comment by wooden070** [comment]
I have the same problem. How can I fix it?

**Comment by qcwthu** [comment]
Hi, sorry for the late reply. Do you still have the same problem? I create a new env for it. However, I don't have this problem...

**Comment by wooden070** [comment]
I still have this problem, directly installing transformers==4.5.0 does not report this error, but there may be other problems. Is it because of an environment problem? Would like to ask about your environment? Thanks!

> Hi, sorry for the late reply. Do you still have the same problem? I create a new env for it. However, I don't have this problem...
