### ISSUE TITLE
Candidate Relations

### ISSUE THREAD

**Issue by njuxinyiwang** [qcwthu/Continual_Fewshot_Relation_Learning#6]
Hello, thanks for your excellent work. 
I want to know how the candidate relations are produced. Are they from the origin dataset? If not, how you choose the candidates for each sample?

**Comment by qcwthu** [comment]
Hi. I don't quite understand your question. Can you explain more on 'candidate relations '?

**Comment by njuxinyiwang** [comment]
Thanks for your reply. 
In the all txt files of the datasets, a list of numbers is set in the front of each sample, the first number is the true label, what do the other numbers mean?
![image](https://user-images.githubusercontent.com/31753517/188768451-98eb92c5-c13e-41d7-80eb-8fdd3557612d.png)

**Comment by qcwthu** [comment]
Hi. They are other negative labels used in this work "Sentence Embedding Alignment for Lifelong Relation Extraction". You can check here (https://aclanthology.org/N19-1086.pdf)
