### ISSUE TITLE
Compared method and evaluation metric

### ISSUE THREAD

**Issue by njuxinyiwang** [qcwthu/Continual_Fewshot_Relation_Learning#7]
Hi, thank for your excellent work.
However, I still have a question about the compared method. From the 'eval_model' function in the provided code, one prediction of an instance is regarded as true as long as its true label score is higher than the scores of the negative labels.  This 'accuracy' metric is not as strict as the 'accuracy' metric used in other CRE models, like RP-CRE (ACL 2021) and following papers since they will compare the true label score with the scores of all seen relations. 

RP-CRE is much earlier than your publication. In your paper, you didn't compare your model with RP-CRE. I'm wondering the reason.

I re-run RP-CRE with your 10-way-5-shot dataset under your evaluation metric (the number selected sample for each relation is set as 1) and I get much higher score in every task (The final task is around 80%). And under the stricter evaluation metric, RP-CRE still achieve a little higher score than your current score. There may be some questions in my applying RP-CRE to your dataset.

Could you please apply RP-CRE to your datasets and provide the scores under fair settings or explain the reason why RP-CRE is not applicable to these datasets? Or could you please provide the scores of your model under the stricter evaluation metric.

Thank you very much!

**Comment by qcwthu** [comment]
Hi. Thanks for your suggestions. I didn't know RP-CRE before. This work was done around Apr 2021 and submitted to EMNLP2021. I followed the evaluation metric in "continual relation learning via episodic memory activation and reconsolidation" (ACL2020).

I will read it first when I have time (busy with ICLR now). BTW, can you tell me your email address?

**Comment by njuxinyiwang** [comment]
Thank you for reply! My email address is [xywang.nju@gmail.com](mailto:xywang.nju@gmail.com). Hope to hear from you!
